version: 2
updates:

  # Maintain dependencies for AitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    labels:
      - "github actions dependencies"

  # Maintain dependencies for Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

    labels:
      - "poetry dependencies"
