image: python:latest


stages:
    - test
    - build
    - deploy

pytest:
    stage: test
    before_script:
        - python --version
        - python -m pip install poetry
        - poetry --version
    script:
        - poetry install --no-interaction --no-ansi
        - poetry run pytest --cov=image_secrets
    tags:
        - docker

docker:
    stage: build
    image: docker:latest
    when: on_success
    only:
        - master
    services:
        - docker:dind
    before_script:
        - docker --version
    script:
        - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
        - docker build . -t "$DOCKER_USERNAME"/imagesecrets
        - docker push "$DOCKER_USERNAME"/imagesecrets:latest
    tags:
        - docker

heroku:
    stage: deploy
    image: ruby:latest
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
          when: always
        - when: never
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
    tags:
        - docker
