image: python:latest

before_script:
    - python --version
    - docker info

stages:
    - install
    - test
    - build

install:
    stage: install
    script:
        - python -m pip install --upgrade pip
        - python -m pip install poetry
        - python -m poetry --version
        - python -m poetry install --no-interaction --no-ansi
    tags:
        - ci

pytest:
    stage: test
    script:
        - python -m poetry run pytest
    tags:
        - ci

docker:
    stage: build
    when: on_success
    script:
        - docker build . -t imagesecrets --rm
    tags:
        - ci
