image: python:latest

before_script:
    - python --version

stages:
    - build
    - test
    - deploy

install:
    stage: build
    script:
        - python -m pip install --upgrade pip
        - python -m pip install poetry
        - python -m poetry --version
        - python -m poetry install --no-interaction --no-ansi
    tags:
        - ci

pytest:
    stage: test
    script:
        - python -m poetry run pytest
    tags:
        - ci

docker:
    stage: deploy
    when: on_success
    before_script:
        - docker info
    script:
        - docker build . -t $DOCKER_TAG
        - docker push $DOCKER_TAG
        - docker run -p 127.0.0.1:8000:80 $DOCKER_TAG  # localhost for now
    tags:
        - ci
