image: python:latest

before_script:
    - python --version

stages:
    - build
    - test

install:
    stage: build
    script:
        - python -m pip install --upgrade pip
        - python -m pip install poetry
        - python -m poetry --version
        - python -m poetry install --no-interaction --no-ansi
    tags:
        - ci

pytest:
    stage: test
    script:
        - python -m poetry run pytest
    tags:
        - ci
