services:
  database:
    image: postgres:latest

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - "8001:5432"

    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "username"
      POSTGRES_DB: "imagesecrets"

    container_name: database

  web:
    build: .

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    env_file: .env

    links:
      - "database:database"

    ports:
      - "8000:8000"

    depends_on:
      - database

    container_name: web

volumes:
  postgres_data:
