[tool.poetry]
name = "imagesecrets-api"
version = "0.1.0"
description = "A tool for encoding and decoding messages into/from images."
authors = ["Lukas Kucera <lukas.kucera.g@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
click = "^7.1.2"
Pillow = "^8.2.0"
fastapi = "^0.63.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
