[tool.poetry]
name = "imagesecrets-api"
version = "0.1.0"
description = "A tool for encoding and decoding messages into/from images."
authors = ["Lukas Kucera <lukas.kucera.g@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Pillow = "^8.2.0"
fastapi = "^0.65.0"
numpy = "^1.20.2"
uvicorn = "^0.13.4"
python-multipart = "^0.0.5"
requests = "^2.25.1"
aiofiles = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
